version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  yabof.cyrhades.fr:
    image: anssi/fcsc2025-pwn-yabof:latest
    ports:
      - ${PORT_SSH}:4000
